version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: spring-boot-demo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres
    ports:
      - "5440:5432"
    networks:
      - vugar-network
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    #    image: ghcr.io/${GITHUB_REPO_OWNER}/kamil-demo-backend:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vugar-demo-db
    depends_on:
      - db
    ports:
      - "8012:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass123
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - vugar-network


networks:
  vugar-network:
    driver: bridge

volumes:
  db-data:
    driver: local